### ISSUE TITLE
Potentially missing file? : /polymer/layout.html

### ISSUE THREAD

**Issue by SockMonster1** [divshot/ele-web#27]
Am I the only one having issues trying to reference layout.html?
I tried to import it using:

```
    <link rel="import" href="../polymer/layout.html">
```

But that doesn't seem to do anything as it does in the Polymer documentation:
https://www.polymer-project.org/docs/polymer/layout-attrs.html
using:

```
    <div vertical layout>
      <div>Alpha</div>
      <div flex>Beta (flex)</div>
      <div>Gamma</div>
    </div>
```

Cheers
Sock

**Comment by mbleigh** [comment]
Actually, just importing `polymer.html` gives you all the layout attributes!

``` html
<link rel="import" href="../polymer/polymer.html">
```

:+1: :wolf:

**Comment by SockMonster1** [comment]
Ahh, I forgot to assign a width and height to the 'vertical layout' container which caused some eerie results. Thank-you!
